### ISSUE TITLE
Unsupported or undefined Opauth strategy

### ISSUE THREAD

**Issue by oitsuki** [uzyn/cakephp-opauth#13]
Unsupported or undefined Opauth strategy - login  on line 120

I try to insert he code inside oscommerce in my login page. Do you have a solution.
I downloaded the pack with facebook, google, twitter and configure only twitter for test.

**Comment by uzyn** [comment]
What's the URL that you visit for authentication?

**Comment by rightawayai** [comment]
I am facing the same issue but with cakephp 2.2.4 , I am trying to access http://localhost/myapp/auth/facebook

**Comment by uzyn** [comment]
@100marks Did you set `Opauth.path`?

``` php
<?php // app/Config/bootstrap.php
Configure::write('Opauth.path', '/myapp/auth/');
```

**Comment by rightawayai** [comment]
after I do that now http://localhost/myapp/auth/facebook  is redirecting to http://localhost/auth/callback#_=_  not  http://localhost/myapp/auth/callback#_=_ ,

If I manually go to the url http://localhost/myapp/auth/callback#_=_ , it throws an error

Error: Opauth-completeController could not be found.

**Comment by uzyn** [comment]
See [Step 6](https://github.com/uzyn/cakephp-opauth/blob/master/README.md).

You'll need to define a route for `/opauth-complete/*`.

**Comment by rightawayai** [comment]
@uzyn it was already defined to Router::connect('/opauth-complete/*',array('controller' => 'users', 'action' => 'opauth_complete'));

if I manually go to http://localhost/myapp/users/opauth_complete, it shows empty array for opauth_data i.e., $this->data

**Comment by uzyn** [comment]
Maybe you can share your bootstrap.php.

**Comment by rightawayai** [comment]
here it is

``` php
<?php

/**
 * Load custom configuration files using the IniReader class
 */

CakePlugin::load('Facebook');



Configure::write('Dispatcher.filters', array(
    'AssetDispatcher',
    'CacheDispatcher'
));

/**
 * Configures default file logging options
 */
App::uses('CakeLog', 'Log');
CakeLog::config('debug', array(
    'engine' => 'FileLog',
    'scopes' => array('notice', 'info', 'debug'),
    'file' => 'debug',
));
CakeLog::config('error', array(
    'engine' => 'FileLog',
    'scopes' => array('warning', 'error', 'critical', 'alert', 'emergency'),
    'file' => 'error',
));

//Configuration for Opauth
CakePlugin::load('Opauth', array('routes' => true, 'bootstrap' => true));
Configure::write('Opauth.path', '/messages/auth/');


Configure::write('Opauth.Strategy.Facebook', array(
   'app_id' => 'xxxxxxxxxxx',
   'app_secret' => 'xxxxxxxxxxxxxxxxxxxx'
)); 

```

**Comment by uzyn** [comment]
Your URL shouldn't be `http://localhost/myapp/auth/facebook` but `http://localhost/messages/auth/facebook` then.

**Comment by rightawayai** [comment]
@uzyn  yes it is that

**Comment by uzyn** [comment]
Sounds like you have it all set. You may want to try with a different browser to just to make sure that cache isn't playing a part in this.

**Comment by rightawayai** [comment]
no luck, I have tried it both in chrome and firefox

**Comment by uzyn** [comment]
Please describe your issue.

**Comment by rightawayai** [comment]
When i go to http://localhost/messages/auth/facebook , I am taken to facebook for authorization when I Click go to app, I return to http://localhost/auth/callback#_=_ and the page says

---

Not Found

The requested URL /auth/callback was not found on this server.

---

If I manually go to http://localhost/messages/users/opauth_complete , i see an empty array for $this->data

**Comment by rightawayai** [comment]
should I open an another bug for this ?

**Comment by uzyn** [comment]
@100marks Yes, please open a bug for this.

Thanks.

**Comment by uzyn** [comment]
Thanks for opening #14.

**Comment by dia2diab** [comment]
thanks for all, you solved my problem

**Comment by manimarangr** [comment]
HI i have the same issue, Can you Help me

**Comment by haridasshinde** [comment]
Unsupported or undefined Opauth strategy
