### ISSUE TITLE
After facebook authorization , the redirection to proper url does not happen

### ISSUE THREAD

**Issue by rightawayai** [uzyn/cakephp-opauth#14]
My app is located at http://localhost/messages, even with all correct configuration

When i go to http://localhost/messages/auth/facebook , I am taken to facebook for authorization when I Click go to app, I return to http://localhost/auth/callback#_=_ and the page says

Not Found

The requested URL /auth/callback was not found on this server.

If I manually go to http://localhost/messages/users/opauth_complete , i see an empty array for $this->data

**Comment by uzyn** [comment]
Thanks @100marks. 

It should be fixed now. Please give it a try and let me know.

Thanks.

**Comment by rightawayai** [comment]
it is redirecting properly now, but $this->data shows error

Array
(
    [error] => Array
        (
            [provider] => Facebook
            [code] => access_token_error
            [message] => Failed when attempting to obtain access token
            [raw] => 
        )

```
[timestamp] => 2013-01-03T12:13:41+00:00
[validated] => 
```

)

**Comment by uzyn** [comment]
You may want to check if your PHP setup has SSL support and that `allow_url_fopen` is enabled at `php.ini`.

You can check that via `phpinfo()`.

**Comment by rightawayai** [comment]
Yes the PHP supports SSL and allow_url_fopen is on

**Comment by uzyn** [comment]
I cannot reproduce this behavior though. I did the same setup as yours, `http://localhost/messages/auth/facebook` and managed to obtain user info from it.

**Comment by rightawayai** [comment]
Is there any setting I need to do in my facebook app, I am using 2.2.4 version of cakephp

**Comment by uzyn** [comment]
The settings on Facebook are mentioned at [README at uzyn/opauth-facebook](https://github.com/uzyn/opauth-facebook/blob/master/README.md).

**Comment by rightawayai** [comment]
@uzyn I have applied these settings

**Comment by rightawayai** [comment]
@uzyn I had the extension=php_openssl.dll uncommented and it is working, Opauth is awesome, thank you for this

**Comment by ceeram** [comment]
readme had a note about this: https://github.com/uzyn/cakephp-opauth/blob/master/README.md#note

**Comment by uzyn** [comment]
@ceeram Haha, I have forgotten about that myself.

Oh well, thinking about it now, it probably makes sense to be within the plugin itself as it contains the callback handler. However, I wouldn't want to be breaking API due to this change. 

Will fix to only update if user does not overwrite it.

**Comment by uzyn** [comment]
Fixed. https://github.com/uzyn/cakephp-opauth/commit/5eb675127bbe29eb7234cf3e29acd09191ed3ff3

**Comment by ghost** [comment]
@uzyn Issue seems to be related to the Security component. Enabling the Security component causes the issue noted above.
