### ISSUE TITLE
Is there a way to access email id of the user in the facebook auth ?

### ISSUE THREAD

**Issue by rightawayai** [uzyn/cakephp-opauth#15]

**Comment by uzyn** [comment]
Add an [email scope](https://developers.facebook.com/docs/reference/login/email-permissions/).

`Configure::read('Opauth.Strategy.Facebook.scope', 'email');`
1. This is unrelated to [cakephp-opauth](https://github.com/uzyn/cakephp-opauth/issues/15)
2. Please do not use GitHub issues for questions, use [Google Groups](https://groups.google.com/forum/#!forum/opauth).
