### ISSUE TITLE
Error 400 Bad Request on Google Strategy

### ISSUE THREAD

**Issue by agponte** [uzyn/cakephp-opauth#17]
I access http://devl.stephenplaud.com/auth/google (feel free to see yourself) and I am redirected to callback, but with this error.  I have tried everything I found on Google Group and here, to no avail.

This is what is returned to the callback method:

array(
    'error' => array(
        'code' => 'access_token_error',
        'message' => 'Failed when attempting to obtain access token',
        'raw' => array(
            'response' => (int) 0,
            'headers' => 'HTTP/1.0 400 Bad Request
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: Fri, 01 Jan 1990 00:00:00 GMT
Date: Wed, 06 Feb 2013 08:15:32 GMT
Content-Type: application/json
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Server: GSE'
        ),
        'provider' => 'Google'
    ),
    'timestamp' => '2013-02-06T03:15:32-05:00',
    'validated' => false
)

**Comment by uzyn** [comment]
Is `allow_url_fopen` and SSL enabled for your PHP?

You may want to check `phpinfo()`.

**Comment by agponte** [comment]
Yes, if you visit the page again now, I enabled PHPINFO() for you to see, but yes they are.

**Comment by uzyn** [comment]
Link to phpinfo?

**Comment by agponte** [comment]
http://devl.stephenplaud.com/pages/phpinfo

**Comment by agponte** [comment]
i also noticed the file_get_contents() call in OpauthStrategy link 402 fails.

**Comment by agponte** [comment]
I got it to work, I had a typo this whole time in the secret!  Sorry and thank you!
