### ISSUE TITLE
Allow Opauth Controller to show /auth/facebook

### ISSUE THREAD

**Issue by igneg** [uzyn/cakephp-opauth#19]
Hi!

if I use AuthComponent (for "standard" user login) that deny access to all, is possibile to set AuthComponent to allow only /auth/facebook?

**Comment by uzyn** [comment]
I'm not sure what you're referring to but you will need to allow access to OpauthController for Opauth to work.

In fact, Opauth plugin should have already done it for you.
See https://github.com/uzyn/cakephp-opauth/blob/master/Controller/OpauthController.php

**Comment by igneg** [comment]
Thanks for reply

When facebook redirect to my application then auth component redirect to standard user login page, because <code>/auth/callback</code> is not allowed by the auth component.

**Comment by igneg** [comment]
SOLVED!

Probably I don't use the latest version. My OpauthController don't have the beforeFilter method

Thanks
