### ISSUE TITLE
Class 'Opauth' nor found

### ISSUE THREAD

**Issue by juarezpaf** [uzyn/cakephp-opauth#2]
Hey there... I am getting an error when I try to go to /auth/facebook and I did follow every step.
Fatal error: Class 'Opauth' not found in /Applications/MAMP/htdocs/phpal-cakephp/app/Plugin/Opauth/Controller/OpauthAppController.php on line 131.

I appreciate your help! Thanks in advance!

**Comment by uzyn** [comment]
I believe you missed out step 2 that deals with got submodule.

If you're not using git, you'll have to download Opauth library from
https://github.com/uzyn/opauth and places it at
APP/Plugin/Opauth/Vendor/Opauth

On 29 May, 2012, at 11:42, "Juarez P. A. Filho"
reply@reply.github.com
wrote:

**Comment by juarezpaf** [comment]
Hey @uzyn I am using Git, but when I rung the git submodule init and update it returns nothing, check this out:

```
➜  phpal-cakephp git:(master) ✗ git submodule init
➜  phpal-cakephp git:(master) ✗ git submodule update
➜  phpal-cakephp git:(master) ✗ 
```

And I thought maybe it will work if I download the opauth and place it inside of app/Plugin/Opauth/Vendor/Opauth but I got another error:

```
Notice (8): Undefined index: action [APP/Plugin/Opauth/Vendor/Opauth/lib/Opauth/Opauth.php, line 113]
Code Context
Opauth::run() - APP/Plugin/Opauth/Vendor/Opauth/lib/Opauth/Opauth.php, line 113
OpauthAppController::index() - APP/Plugin/Opauth/Controller/OpauthAppController.php, line 31
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - CORE/Cake/Controller/Controller.php, line 485
Dispatcher::_invoke() - CORE/Cake/Routing/Dispatcher.php, line 103
Dispatcher::dispatch() - CORE/Cake/Routing/Dispatcher.php, line 85
[main] - APP/webroot/index.php, line 92
```

Am I doing something wrong here, isn't it? Thanks in advance!

**Comment by uzyn** [comment]
Did you run `git submodule init` from APP/Plugin/Opauth ?

That notice seems to be okay. To avoid the notice, you can specifically go to `http://DOMAIN/auth/facebook/request`.

Let me know if it's working for you.
