### ISSUE TITLE
/auth/callback - Opauth-completeController could not be found

### ISSUE THREAD

**Issue by elogicmedia** [uzyn/cakephp-opauth#21]
Hi,

I have set this up with the facebook login, I click my facebook login button if goes off to facebook and comes back to mydomain.com/auth/callback.

I am getting this error on that page:

Missing Controller

Error: Opauth-completeController could not be found.

Error: Create the class Opauth-completeController below in file: app/Controller/Opauth-completeController.php

<?php
class Opauth-completeController extends AppController {

}

within routes.php I have:

   Router::connect(
   '/opauth-complete/*',
        array('controller' => 'users', 'action' => 'opauth_complete')
     );

If I go to domain.com/users/opauth_complete I am getting an empty array.

Any idea what is going on?

Thanks

**Comment by elogicmedia** [comment]
I had the paths wrong in facebook causing my issue. This is now working.

**Comment by morelazers** [comment]
What was the change you made to the URL in facebook? I'm having the same issue.

**Comment by elogicmedia** [comment]
domain.com/opauth-complete/

I oriignally put in: domain.com/opauth_complete/

**Comment by morelazers** [comment]
I still don't quite understand, was this in the facebook developer console or the facebook strategy?

I can't see anywhere to put the callback URL in the dev console

**Comment by uzyn** [comment]
@morelazers Maybe you can share what issue are you getting.

**Comment by morelazers** [comment]
I'm developing locally, and when I go to http://localhost/auth/facebook/ (or /auth/google/ for that matter) the request goes off then comes back to http://localhost/auth/callback where I get the error described above by elogicmedia.

I have:

Router::connect(
   '/opauth-complete/*', 
   array('controller' => 'users', 'action' => 'opauth_complete')
);

in my routes file.

I have tried to add http://localhost/opauth-complete/ as a valid redirect URI in the dev console but then I get an error about the URI from facebook when I access /auth/facebook/

Sorry if I'm not being specific enough, I'm really new to all this

**Comment by uzyn** [comment]
Did you load both the routes and bootstrap when you load the plugin?

`CakePlugin::load('Opauth', array('routes' => true, 'bootstrap' => true));`

**Comment by morelazers** [comment]
Yeah I have that in my app/config/bootstrap.php above the settings for the individual strategies.

It seems as though the routes are not being loaded but the URL is showing as http://localhost/auth/callback/

**Comment by morelazers** [comment]
I found the issue: I was specifying the route after calling `CakePlugin::routes();` in my `routes.php` file

**Comment by manimarangr** [comment]
HI i have followed the above, but still i am getting the issue:
from :http://localhost/delyver/auth/facebook
returning to this:
http://localhost/auth/callback#_=_

I am using cakephp 2.5.3

**Comment by basantk** [comment]
i have the same assue....geting.. i have tried all things that u told...please give the axact solution for his

**Comment by sumitkanoje** [comment]
Solution to this issue is,
You should write

```
Router::connect(
        '/opauth-complete/*',
        array('controller' => 'users', 'action' => 'opauth_complete')
);
```

Before calling  `CakePlugin::routes();`

inside `routes.php` file.

In my case it worked.
