### ISSUE TITLE
Cakephp Opauth with Google

### ISSUE THREAD

**Issue by AlessandroMinoccheri** [uzyn/cakephp-opauth#22]
I have a site developed in cakephp. I wanna be able to login with facebook, Twitter and Google. With Facebook I haven't problem but with Google I receive this error:

Fatal Error
Error: GoogleStrategy config parameter for "client_id" expected.  
File: /my_site/html/app/Plugin/Opauth/Vendor/Opauth/lib/Opauth/OpauthStrategy.php  
Line: 201
Notice: If you want to customize this error message, create app/View/Errors/fatal_error.ctp
I have follow the instructions at the letter from this page: https://github.com/opauth/google

And I have copied into my bootstrap.php (like with facebook) my app Id like this:

Configure::write('Opauth.Strategy.Facebook', array(
   'app_id' => 'FBID',
   'app_secret' => 'FBPAssword'
));

Configure::write('Opauth.Strategy.Google', array(
   'app_id' => 'GoogleID',
   'app_secret' => 'GooglePWD'
)); 
Why I retrieve this error?

Thanks?

I think that the problem I have download a version of google opauth not for cakephp is possible?

**Comment by ceeram** [comment]
As the readme you link to shows, you need to set client_id instead of
app_id, just as the error tells you.

2013/7/11 AlessandroMinoccheri notifications@github.com

**Comment by AlessandroMinoccheri** [comment]
Oh man... Mine error sorry if you have lost time!
Thanks a lot!
