### ISSUE TITLE
Error: Unsupported or undefined Opauth strategy - auth

### ISSUE THREAD

**Issue by AlessandroMinoccheri** [uzyn/cakephp-opauth#24]
I have seen this error again in other issue but I haven't find the solution for me.
I have already installed opauth and now when U try to login with facebook I retrieve this error:
Error: Unsupported or undefined Opauth strategy - auth  
File: /Users/my_user/Sites/my_app/app/Plugin/Opauth/Vendor/Opauth/lib/Opauth/Opauth.php 
Line: 120

This is my bootstrap:
CakePlugin::load('Opauth', array('routes' => true, 'bootstrap' => true));
//Configure::write('Opauth.path', '/my_app/auth/');
Configure::write('Opauth.Strategy.Facebook', array(
   'app_id' => 'XXXX',
   'app_secret' => 'XXXX'
));

I have tried to uncomment the line of COnfigure::Write but after tell me that the url isn't valid when I authenticate in facebook

What can I do to solve this?
I don't understand because some weeks ago seems that this code working fine

**Comment by uzyn** [comment]
You'll firstly have to uncomment `Configure::write('Opauth.path', '/my_app/auth/');`.

What's the error you get after that/

**Comment by AlessandroMinoccheri** [comment]
Now I can insert username and password in facebook ut on submit I retrieve an error that the url inserted isn't in the app configuration

**Comment by uzyn** [comment]
Screenshot or pastebin of the actual error?

**Comment by AlessandroMinoccheri** [comment]
the actual error is: (translate from italian to english)
The URL you entered is not permitted by the application configuration.: One or more of the addresses entered are not allowed by the application settings. Must match the address of the Home Page or the Website or the domain must be a subdomain of one of the domains.

**Comment by AlessandroMinoccheri** [comment]
No answer? :(

**Comment by ceeram** [comment]
I have never seen either cakephp or opauth generate such an error message.
Do you have a stack trace perhaps?
Op 2 aug. 2013 17:07 schreef "AlessandroMinoccheri" <
notifications@github.com> het volgende:

**Comment by Raunter** [comment]
Delete or comment that line: Configure::write('Opauth.Strategy', array());
