### ISSUE TITLE
The URL you entered is not permitted by the application configuration.

### ISSUE THREAD

**Issue by AlessandroMinoccheri** [uzyn/cakephp-opauth#25]
Hi all, I have a little problem inside my app whn I try to login by facebbok.
I am in localhost and I don't know of this can be a problem.
But the error is that when I click login with facebook
The URL you entered is not permitted by the application configuration.: One or more of the URLs entered are not allowed by the application settings. The URL must match that of the Website or the main page of the application and the domain must be a subdomain of one of the domains.

Here is my bootstrap.php the part of facebook
CakePlugin::load('Opauth', array('routes' => true, 'bootstrap' => true));
Configure::write('Opauth.path', '/site.com/auth/');
Configure::write('Opauth.Strategy.Facebook', array(
   'app_id' => 'XXX',
   'app_secret' => 'XXX'
));

This is the part of routes.php
Router::connect( '/opauth-complete/*', array('controller' => 'users', 'action' => 'opauth_complete'));

I have an action insde controller UsersController.php called opauth_complete.

What I'm wrong?

Thanks

**Comment by uzyn** [comment]
The error comes from Facebook. 

You'll have to enter your domain(s) at app domains settings for your Facebook app. (https://developers.facebook.com/apps/)

**Comment by AlessandroMinoccheri** [comment]
Yes it was that the problem 
Thanks
