### ISSUE TITLE
Undefined index: strategy

### ISSUE THREAD

**Issue by piotr0beschel** [uzyn/cakephp-opauth#3]
Notice (8): Undefined index: strategy [APP\Plugin\Opauth\Vendor\Opauth\lib\Opauth\Opauth.php, line 120]
Code Context
Opauth::run() - APP\Plugin\Opauth\Vendor\Opauth\lib\Opauth\Opauth.php, line 120
OpauthAppController::index() - APP\Plugin\Opauth\Controller\OpauthAppController.php, line 31
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - CORE\Cake\Controller\Controller.php, line 485
Dispatcher::_invoke() - CORE\Cake\Routing\Dispatcher.php, line 103
Dispatcher::dispatch() - CORE\Cake\Routing\Dispatcher.php, line 85
[main] - APP\webroot\index.php, line 93
Fatal Error (256): Unsupported or undefined Opauth strategy -  [APP\Plugin\Opauth\Vendor\Opauth\lib\Opauth\Opauth.php, line 120]
Code Context
    public function index(){

```
    $this->_loadOpauth();

    $this->Opauth->run();
```

Opauth::run() - APP\Plugin\Opauth\Vendor\Opauth\lib\Opauth\Opauth.php, line 120
OpauthAppController::index() - APP\Plugin\Opauth\Controller\OpauthAppController.php, line 31
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - CORE\Cake\Controller\Controller.php, line 485
Dispatcher::_invoke() - CORE\Cake\Routing\Dispatcher.php, line 103
Dispatcher::dispatch() - CORE\Cake\Routing\Dispatcher.php, line 85
[main] - APP\webroot\index.php, line 93

Any ideas?

**Comment by uzyn** [comment]
@piotr0beschel 

I'm guessing your CakePHP app is not at DocumentRoot (eg. http://localhost) but at a directory (eg. http://localhost/cakeapp).

If that's true, please try addding this line to your app's `Config/bootstrap.php`:

`Configure::write('Opauth.path', '/cakeapp/auth/');`

**Comment by piotr0beschel** [comment]
Correct. Thank you very much

**Comment by naveenkrsh68** [comment]
Message: Unsupported or undefined Opauth strategy - login

I got this issue. please help me

**Comment by uzyn** [comment]
@naveenkrsh68 That simply means that you did not set up Opauth properly. Please go through the steps properly on the setup.
