### ISSUE TITLE
Table opauth_settings for model OpauthSetting was not found in datasource default.

### ISSUE THREAD

**Issue by polen2005** [uzyn/cakephp-opauth#34]
How fix this error?

Missing Database Table
Error: Table opauth_settings for model OpauthSetting was not found in datasource default.

this is the line of code who generate this error (model GoogleApi.php in Google plugin):
$config = ClassRegistry::init('Opauth.OpauthSetting')
                ->findByName($this->_strategy);

**Comment by uzyn** [comment]
GoogleApi.php is not part of this plugin.

**Comment by uzyn** [comment]
You should be checking with whomever that authored GoogleApi.php, as that is the root of the error that you're reporting.

**Comment by uzyn** [comment]
@polen2005 Those are unrelated to this plugin. You're asking at the wrong place.
