### ISSUE TITLE
3.0 Upgrade

### ISSUE THREAD

**Issue by jadb** [uzyn/cakephp-opauth#46]
Are there any plans to upgrade this plugin to 3.0?

**Comment by ceeram** [comment]
@jadb for opauth 1.0 it is no longer really needed as lots of cruft has
been removed in 1.0, so not really, but feel free to do so for opauth 0.x

2015-01-14 16:29 GMT+01:00 Jad BITAR notifications@github.com:

**Comment by jadb** [comment]
@ceeram i noticed (using it on [StillMaintained](https://github.com/stillmaintained/stillmaintained/blob/master/src/Controller/OpauthController.php) which was moved from Ruby to Cake3) - but you know how most of us are lazy like that ;)

Anyhow, there is already one done for Cake3 using 1.x - no need for 0.x support (I'd rather put effort in upgrading strategies to 1.x instead if I had time, last time i checked they didn't all have 1.x branches).
