### ISSUE TITLE
Why don't submodule the strategies ?

### ISSUE THREAD

**Issue by steinkel** [uzyn/cakephp-opauth#5]
It could be easy install and update.

**Comment by uzyn** [comment]
The reason why strategies are not submoduled from the main Opauth package and this CakePHP plugin is similar to why WordPress does not include submodule all known plugins in their main package.

Opauth is meant to be an open framework where anyone can contribute strategies to, even overlapping ones (eg. multiple Google strategies by different authors). For now, the number of strategies are still rather limited, when the numbers increase, say to the range of hundreds, I'm not sure if that would still be a good idea anymore.

**Comment by steinkel** [comment]
Understood :)
Then we could load the strategies from the base app/Plugin folder, so we
keep all git clean to setup...

2012/8/9 U-Zyn Chua notifications@github.com

**Comment by steinkel** [comment]
Finally i've added the strategies into the Vendors folder, and used a custom setup to set the base folder for Opauth strategies in my bootstrap file.
This keeps all submodules clean.

**Comment by uzyn** [comment]
Cool. You can use `strategy_dir` to set the strategy directories too.

Reference: https://github.com/uzyn/opauth/wiki/Opauth-configuration
